services:
  - type: web
    name: secure-assignment-evaluator
    env: python
    plan: free
    buildCommand: pip install -r deployment_requirements.txt && python -c "import nltk; nltk.download('punkt')"
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true