[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4e89ae"
backgroundColor = "#1d1e2e"
secondaryBackgroundColor = "#252640"
textColor = "#ffffff"